# Generated by Django 3.2.4 on 2021-06-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0002_auto_20210610_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
